### ISSUE TITLE
"Some tests are failing"

### ISSUE THREAD

**Issue by haadcode** [ipfs-shipyard/ipfs-pubsub-room#17]
When trying to run the tests, they error with the following error message (see below). I took a fresh clone and run npm i && npm test. Looks like a mocha/aegir error to me.

Any suggestions how to fix the tests?

```
haad:~/code/ipfs-pubsub-room$ npm test

> ipfs-pubsub-room@0.4.0 test /Users/haad/code/ipfs-pubsub-room
> npm run lint && npm run test:browser


> ipfs-pubsub-room@0.4.0 lint /Users/haad/code/ipfs-pubsub-room
> aegir lint



> ipfs-pubsub-room@0.4.0 test:browser /Users/haad/code/ipfs-pubsub-room
> aegir test --target browser --dom

Test Browser


Chrome 62.0.3202 (Mac OS X 10.11.6) LOG: 'Swarm listening on', '/dns4/star-signal.cloud.ipfs.team/wss/p2p-webrtc-star/ipfs/QmZxPaE9QCnXYAxQ3vSrVZnkyQW7tef9GVVyCeTe11Bowo'
Chrome 62.0.3202 (Mac OS X 10.11.6) LOG: 'Swarm listening on', '/dns4/star-signal.cloud.ipfs.team/wss/p2p-webrtc-star/ipfs/QmTEJ7KnSKWuihB6B9sBABDwywKHkv4qvmTP3uqLQFVo8M'
  sync
    1) can create a room, and they find each other
    2) has peer
    3) can broadcast
    4) can send private message
    5) can be stopped


  0 passing (27s)
  5 failing

30 10 2017 14:46:08.054:ERROR [karma]: TypeError: test.titlePath is not a function
    at /Users/haad/code/ipfs-pubsub-room/node_modules/mocha/lib/reporters/base.js:227:10
    at Array.forEach (<anonymous>)
    at Function.exports.list (/Users/haad/code/ipfs-pubsub-room/node_modules/mocha/lib/reporters/base.js:167:12)
    at Spec.Base.epilogue (/Users/haad/code/ipfs-pubsub-room/node_modules/mocha/lib/reporters/base.js:344:10)
    at emitNone (events.js:110:20)
    at EventEmitter.emit (events.js:207:7)
    at Reporter.onRunComplete (/Users/haad/code/ipfs-pubsub-room/node_modules/karma-mocha-own-reporter/index.js:174:16)
    at Server.<anonymous> (/Users/haad/code/ipfs-pubsub-room/node_modules/karma/lib/events.js:13:22)
    at emitTwo (events.js:130:20)
    at Server.emit (events.js:213:7)
    at emitRunCompleteIfAllBrowsersDone (/Users/haad/code/ipfs-pubsub-room/node_modules/karma/lib/server.js:295:12)
    at Server.<anonymous> (/Users/haad/code/ipfs-pubsub-room/node_modules/karma/lib/server.js:326:7)
    at emitOne (events.js:115:13)
    at Server.emit (events.js:210:7)
    at Server.<anonymous> (/Users/haad/code/ipfs-pubsub-room/node_modules/karma/lib/server.js:309:12)
    at emitTwo (events.js:130:20)
Some tests are failing
Error: Some tests are failing
    at Server (/Users/haad/code/ipfs-pubsub-room/node_modules/aegir/src/test/browser.js:12:16)
    at removeAllListeners (/Users/haad/code/ipfs-pubsub-room/node_modules/karma/lib/server.js:380:7)
    at Server.<anonymous> (/Users/haad/code/ipfs-pubsub-room/node_modules/karma/lib/server.js:391:9)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:110:20)
    at Server.emit (events.js:207:7)
    at emitCloseNT (net.js:1646:8)
    at _combinedTickCallback (internal/process/next_tick.js:135:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ipfs-pubsub-room@0.4.0 test:browser: `aegir test --target browser --dom`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ipfs-pubsub-room@0.4.0 test:browser script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/haad/.npm/_logs/2017-10-30T13_46_08_757Z-debug.log
npm ERR! Test failed.  See above for more details.
```

**Comment by VictorBjelkholm** [comment]
Seems like this has been fixed already, could you try out the latest aegir release? PR for the fix is here: https://github.com/ipfs/aegir/pull/164

**Comment by haadcode** [comment]
@VictorBjelkholm thanks for the reply! It looks like ipfs-pubsub-room uses the latest aegir (v12.1.1). I don't seem to find ipfs/aegir#164 from the [commits](https://github.com/ipfs/aegir/commits/master). Is it really merged and published to npm? Any suggestions how to proceed?

```
haad:~/code/ipfs-pubsub-room$ npm ls aegir
ipfs-pubsub-room@0.4.0 /Users/haad/code/ipfs-pubsub-room
└── aegir@12.1.1
```

**Comment by VictorBjelkholm** [comment]
Ah, that's true, it has been merged but not yet released.. You could try `npm install ipfs/aegir#9ddadf93cd08846eb965cbd75e156ee09c140ca9` to install that version directly.

**Comment by haadcode** [comment]
Thanks @VictorBjelkholm. Using the commit above seems to get rid of the original error, but I get a bunch of new ones. Unfortunately I don't have time right now to dig deeper. Let's leave this open for now to make sure we fix it eventually.

**Comment by haadcode** [comment]
I think latest aegir fixes the issues. There's a PR that has the latest aegir and the tests are now running: https://github.com/ipfs-shipyard/ipfs-pubsub-room/pull/22

**Comment by haadcode** [comment]
This was fixed. Thank you erveyone!
